CREATE TABLE doctors(
   doctor_id VARCHAR(8) NOT NULL PRIMARY KEY
  ,lastname   VARCHAR(30) NOT NULL
  ,firstname  VARCHAR(30) NOT NULL
  ,years_of_exp numeric(4,0) check (years_of_exp>0 and Years_of_exp<100)
  ,specialty    VARCHAR(100) NOT NULL
);
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('73745487','Pachucki','Josiephine',2,'Congenital Cardiac Surgery Thoracic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('69114735','Dutter','Coy',90,'Orthopaedic Sports Medicine Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('49275000','Farrukh','Sebastian',48,'Endovascular Surgical Neuroradiology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('89021273','Vongprachanh','Maxwell',95,'Geriatric Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('45895041','Kobasa','Ramona',61,'Endovascular Surgical Neuroradiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('52789533','Koogler','Nathaniel',82,'Hematology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75353173','Heldreth','Jemima',48,'Pediatric Critical Care Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('80570796','Cronic','Orla',4,'Child & Adolescent Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('33147852','Halilovic','Isaiah',35,'Pediatric Otolaryngology Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('61308895','Us','Waverly',25,'Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('66800269','Mosholder','Vergil',55,'Thoracic Surgery-Integrated Thoracic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('84097469','Lenczewski','Guadalupe',73,'Orthopaedic Surgery of the Spine Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('38003468','Gaik','Rena',48,'Hand Surgery Plastic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('70504819','Kisler','Carl',88,'Pain Medicine Anesthesiology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('89714328','Fam','Julie',3,'Clinical & Laboratory Immunology Allergy & Immunology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('36538359','Reemsnyder','Placido',95,'Otology - Neurotology Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('45806042','Fiegener','Evans',6,'Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('61965300','Camarano','Raul',87,'Rheumatology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('26788364','Abdulla','Lera',73,'Thoracic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('35369228','Samorano','Lyman',78,'Orthopaedic Sports Medicine Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('37310093','Chaddick','Rennie',83,'Pediatric Emergency Medicine Emergency Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('84388188','Zimmerly','Chaney',64,'Abdominal Radiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('29430583','Papula','Buna',74,'Endocrinology, Diabetes & Metabolism Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('17899625','Berly','Lady',20,'Ophthalmology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51087838','Pettingell','Lloyd',15,'Vascular Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('31662429','Verhoef','Drew',25,'Transplant Hepatology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('42891265','Nevills','Roberta',11,'Forensic Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('41822275','Pautler','Octavie',86,'Endocrinology, Diabetes & Metabolism Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('50387120','Libey','Wellington',12,'Sports Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('80178135','Baynton','Isaiah',37,'Female Pelvic Medicine & Reconstructive Surgery Obstetrics & Gynecology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('52323564','Lassere','Marshall',60,'Musculoskeletal Oncology Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('36717458','Stalter','Orel',53,'Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51060768','Scheiter','Adolfo',7,'Forensic Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('44715341','Haddad','Zula',64,'Child & Adolescent Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('16187770','Awtrey','Jordan',34,'Medical Microbiology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('83228195','Kelker','Flonnie',64,'Pediatric Hematology-Oncology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('59347810','Ne','Eugenie',52,'Vascular Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53235608','Grachek','Hosea',22,'Neurological Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('41233982','Islamovic','Vila',28,'Sports Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('21432165','Martindell','Seth',27,'Infectious Disease Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('60943275','Cromarty','Lucretia',89,'Procedural Dermatology Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('82878006','Nanz','Cornelius',6,'Pain Medicine Physical Medicine & Rehabilitation');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('74196419','Fintel','Jesusita',76,'Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75347325','Cockman','Rex',71,'Surgical Critical Care Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('59288089','Gentile','Eufemia',27,'Pediatric Nephrology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('13853044','Rueth','Rene',88,'Neuropathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51728036','Breckinridge','Estel',16,'Pediatric Emergency Medicine Emergency Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('81375033','Sant','Refugio',27,'Blood Banking - Transfusion Medicine Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('55345942','Fraase','Leora',98,'Pediatric Rheumatology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('40497224','Zrust','Retta',95,'Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('79131413','Danjou','Bennett',73,'Neurological Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51062899','Hannahs','Floyd',33,'Endovascular Surgical Neuroradiology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53198121','Elg','Horatio',51,'Sleep Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('10133637','Pogatchnik','Juliana',37,'Addiction Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('52340558','Armwood','Calvin',83,'Orthopaedic Sports Medicine Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('38995452','Duphily','Nobie',2,'Cardiothoracic Radiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('58829703','Arntson','Cecil',35,'Child Abuse Pediatrics Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('19439463','Zarkowski','Blanch',6,'Sports Medicine Family Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53880876','Provow','Ole',36,'Allergy & Immunology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('34279827','Johnsonlee','Otha',69,'Abdominal Radiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('32670325','Pandy','Clem',50,'Pediatric Cardiology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('47597856','Scumaci','Margaret',41,'Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('20492415','Schnyer','Earle',47,'Pediatric Infectious Diseases Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('64702447','Mcalear','Drew',4,'Endovascular Surgical Neuroradiology Neurological Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('88087467','Pervaiz','Myrna',28,'Thoracic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('26754436','Verbruggen','Nannie',12,'Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('55964973','Reichle','Arthur',43,'Forensic Pathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('43598444','Dalen','Victoria',39,'Craniofacial Surgery Plastic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('81908049','Wise','Clifton',36,'Sports Medicine Emergency Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('34090608','Kawate','Pat',46,'Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('69436263','Levinsky','Sophia',78,'Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('38183604','Apruzzese','Delmas',3,'Medical Microbiology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('14774225','Helmes','Belma',95,'Pediatric Gastroenterology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('12076374','Amans','Vola',9,'Radiation Oncology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('72843162','Random','Madge',91,'Geriatric Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('55833518','Kuligowski','Elmer',61,'Cytopathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('86760478','Moc','Prentice',3,'Otology - Neurotology Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('62354355','Hanns','Magie',24,'Hand Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('21044781','Writesel','Classie',82,'Pediatric Urology Urology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('31895651','Fan','Ward',8,'Urology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('31215490','Soldi','Buren',48,'Radiation Oncology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('78189682','Semin','Gene',97,'Hand Surgery Plastic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('63633849','Hazelrig','Orlo',33,'Family Practice');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('24377331','Herold','Spurgeon',69,'Hematology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('40202154','Odear','Worth',45,'Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('33067232','Schnier','Carlos',87,'Sports Medicine Physical Medicine & Rehabilitation');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('30674180','Hoines','Zena',15,'Adolescent Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('40699585','Elwing','Fredericka',76,'Pediatric Transplant Hepatology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('62760544','Gafney','Marry',7,'Child Abuse Pediatrics Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('41747191','Daspit','Annamarie',1,'Advanced Heart Failure & Transplant Cardiology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('66619458','Bune','Veva',16,'Endovascular Surgical Neuroradiology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('20890997','Payamps','Artie',67,'Procedural Dermatology Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('28220870','Bodek','Lorretta',42,'Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('60683418','Spanish','Arne',6,'Radiation Oncology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('29368816','Allenson','Mavis',92,'Transplant Hepatology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('72507833','Courser','Neda',84,'Hematology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('43960103','Siverson','Lilly',81,'Ophthalmic Plastic & Reconstructive Surgery Ophthalmology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('49491990','Janowiecki','Nellie',14,'Hand Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('42609521','Hatzinger','Vernie',90,'Forensic Pathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('61316469','Schaedel','Jacinta',70,'Medical Toxicology Preventive Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('24011646','Lauren','Vena',6,'Clinical Cardiac Electrophysiology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('15909205','Binette','Stewart',69,'Hematology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('87523250','Bellmyer','Pollie',63,'Medical Genetics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('62592248','Manteiga','Isabel',2,'Medical Toxicology Emergency Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('84619450','Jakupovic','Josephine',4,'Ophthalmic Plastic & Reconstructive Surgery Ophthalmology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('57119280','Armster','Ivy',71,'Obstetrics & Gynecology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('82117147','Herard','Marguerite',73,'Orthopaedic Trauma Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('46386231','Meemken','Deanna',49,'Pediatric Nephrology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('37687770','Floriani','Judge',44,'Chemical Pathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('17045349','Abdelrahman','Ossie',11,'Dermatopathology Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('13165893','Belshaw','Glenna',88,'Pediatric Hematology-Oncology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('33919552','Horvath','Iris',3,'Pediatric Pathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('86533887','Branick','Emil',43,'Musculoskeletal Oncology Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('77767937','Molumby','Hester',48,'Physical Medicine & Rehabilitation');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('13681132','Hockenbery','Iris',35,'Sports Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('76438838','Bohrn','Loring',75,'Geriatric Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('19421830','Beerman','Nealy',97,'Neonatal-Perinatal Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('52423322','Stocum','Georgeanna',47,'Foot & Ankle Orthopaedics Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('86603892','Orebaugh','Oris',9,'Physical Medicine & Rehabilitation');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('20183510','Irlbeck','Obe',94,'Pediatric Urology Urology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('21560795','Dunnings','Lem',28,'Pediatric Anesthesiology Anesthesiology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75091217','Myers','Ula',85,'Pediatric Cardiology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('42629299','Heniser','Benjaman',5,'Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('18313975','Piet','Evelina',53,'Pulmonary Disease & Critical Care Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('27227551','Sabens','Cyrilla',9,'Otology - Neurotology Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('31167518','Frament','Gracia',6,'Family Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('67259626','Rimmel','Fay',3,'Pediatric Critical Care Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('39264519','Giambruno','Wilna',65,'Clinical Neurophysiology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('71223527','Devlin','Kathryne',93,'Sports Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('42636154','Rubbelke','Soloman',36,'Pediatric Emergency Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('10101383','Okerlund','Hixie',78,'Clinical Cardiac Electrophysiology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('43039497','Sandage','Margarette',26,'Nuclear Radiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('39770284','Lofstedt','Syd',25,'Endovascular Surgical Neuroradiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('36223691','Picar','Parley',5,'Child Neurology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('25115494','Oliva','Norene',92,'Spinal Cord Injury Medicine Physical Medicine & Rehabilitation');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('88941946','Sabus','Rush',27,'Child Neurology Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75822600','Mullvain','Caleb',59,'Pediatric Hematology-Oncology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53102269','Huskins','Rexford',98,'Plastic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('45474685','Krienert','Theron',35,'Medical Genetics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('11402166','Bleichner','Freddie',9,'Adolescent Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('44169435','Cohen','Ira',40,'Interventional Cardiology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('63255064','Phinnessee','Marianne',15,'Sports Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('65284797','Burch','Orrin',29,'Pain Medicine Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('12860860','Krontz','Diana',75,'Surgical Critical Care Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53640562','Roiz','Lena',85,'Pediatric Rheumatology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('22870762','Mema','Tim',22,'Pediatric Emergency Medicine Emergency Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('60821962','Nedza','Camille',62,'Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('44539977','Coderre','Omar',25,'Addiction Psychiatry Psychiatry');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('18346229','Quaile','Rae',76,'Congenital Cardiac Surgery Thoracic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('11985868','Wissert','Fronia',5,'Cytopathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('67504449','Eckberg','Handy',85,'Child Abuse Pediatrics Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('63385418','Rosenburg','Harry',58,'Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('46741047','Bratman','Ozella',25,'Neuropathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('76801720','Saberi','Walter',88,'Musculoskeletal Oncology Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('27780537','Thudium','Emily',90,'Critical Care Medicine Anesthesiology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('85334103','Denmark','Neoma',87,'Vascular Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('53263188','Mcstay','Arturo',23,'Neonatal-Perinatal Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('43054997','Roumeliotis','Theresa',88,'Pediatric Gastroenterology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('12748239','Abbatoy','William',23,'Pediatric Urology Urology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('26206729','Zecha','Samual',4,'Allergy & Immunology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('72427503','Andrle','Justus',43,'Anesthesiology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('87598639','Hasken','Kelly',30,'Cardiothoracic Radiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('17501858','Grassano','Stephen',50,'Otology - Neurotology Otolaryngology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('36166773','Threlkeld','Roxanna',16,'Nuclear Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('80537977','Iacoviello','Jewel',60,'Cardiovascular Disease Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75286611','Gummersall','Frankie',29,'Musculoskeletal Oncology Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51600051','Berends','Ephriam',49,'Neuromuscular Medicine Neurology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('63212375','Creacy','Russel',89,'Adult Reconstructive Orthopaedics Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('22095429','Maffie','Carolina',78,'Hematology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('40251841','Lazaris','Oswald',41,'Neuroradiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('65901690','Rouillier','Jessica',39,'Pediatric Transplant Hepatology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('18869367','Parascandola','Drucilla',55,'Pediatric Surgery Surgery-General');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('14862717','Turak','Cleotilde',78,'Molecular Genetic Pathology Medical Genetics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('41086373','Mastin','Cedric',16,'Nuclear Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('30082812','Streif','Unknown',60,'Urology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('10724115','Data','Elliott',33,'Adolescent Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('32313432','Beco','Augusta',12,'Musculoskeletal Oncology Orthopaedic Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('74428810','Denes','Omer',66,'Geriatric Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('49029433','Ludington','Lillia',31,'Pediatric Pulmonology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('11937321','Houghland','Hampton',52,'Adolescent Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('86877679','Grix','Myrta',77,'Pediatric Critical Care Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('56814150','Ask','Juliette',19,'Endovascular Surgical Neuroradiology Radiology-Diagnostic');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('23643240','Hospelhorn','Johnny',20,'Geriatric Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('45372204','Manderfeld','Wayman',48,'Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('27303402','Thanner','Micheal',39,'Neonatal-Perinatal Medicine Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('41721043','Evenstad','Zeno',84,'Neurological Surgery');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('20558792','Nathan','Nona',38,'Geriatric Medicine Family Practice');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('75937593','Mcbrady','Cleo',13,'Pulmonary Disease & Critical Care Medicine Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('51359183','Farria','Coleman',65,'Blood Banking - Transfusion Medicine Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('44336609','Lababidi','Morton',33,'Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('65192784','Aguiler','Bridget',74,'Pediatric Gastroenterology Pediatrics');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('72557893','Presendieu','Hazel',78,'Neuropathology Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('33992279','Inoue','Sidonia',40,'Ophthalmic Plastic & Reconstructive Surgery Ophthalmology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('44347784','Klontz','Joan',12,'Blood Banking - Transfusion Medicine Pathology-Anatomic & Clinical');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('37526739','Mascola','Cam',92,'Procedural Dermatology Dermatology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('26227004','Budig','Cara',47,'Anesthesiology');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('28721746','Pich','Arley',59,'Oncology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('86145228','Kardaras','Melva',86,'Nuclear Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('49864926','Jazo','Benedict',85,'Clinical Cardiac Electrophysiology Internal Medicine');
INSERT INTO doctors(doctor_id,lastname,firstname,years_of_exp,specialty) VALUES ('15967137','Misko','Willis',96,'Endovascular Surgical Neuroradiology Neurological Surgery');
